{
 "title": "Fruits",
 "time": { "from": "now-15m", "to": "now" },
 "refresh": "30s",
 "panels": [
  {
   "title": "Consumed vs Produced (per second)",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 0 },
   "targets": [
    {
     "expr": "sum(rate(fruit_produced[$__rate_interval]))",
     "legendFormat": "Produced"
    },
    {
     "expr": "sum(rate(fruit_consumed[$__rate_interval]))",
     "legendFormat": "Consumed"
    },
    {
     "expr": "sum(rate(fruit_produced[$__rate_interval]))-sum(rate(fruit_consumed[$__rate_interval]))",
     "legendFormat": "Diff"
    }
   ]
  },
  {
   "title": "Fruit produced (last 10 minutes)",
   "type": "bargauge",
   "gridPos": { "h": 6, "w": 12, "x": 12, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum by (type) (increase(fruit_produced[10m]))",
     "legendFormat": "{{type}}"
    }
   ]
  },
  {
   "title": "Fruit consumed (last 10 minutes)",
   "type": "bargauge",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 6 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum by (type) (increase(fruit_consumed[10m]))",
     "legendFormat": "{{type}}"
    }
   ]
  },
  {
   "title": "Fruit Forwarded by instance (per second)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 9 },
   "targets": [
    {
     "expr": "sum by (exported_job) (rate(fruit_forwarded[$__rate_interval]))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Total Fruit Produced (last 10 minutes)",
   "type": "stat",
   "gridPos": { "h": 3, "w": 4, "x": 12, "y": 13 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(increase(fruit_consumed[10m]))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Total Fruit Produced (last 10 minutes)",
   "type": "stat",
   "gridPos": { "h": 3, "w": 4, "x": 16, "y": 13 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(increase(fruit_produced[10m]))",
     "legendFormat": "__auto"
    }
   ]
  }
 ]
}