{
 "title": "RabbitMq",
 "time": { "from": "now-5m", "to": "now" },
 "refresh": "5s",
 "panels": [
  {
   "title": "Messages published / second",
   "type": "timeseries",
   "gridPos": { "h": 13, "w": 18, "x": 0, "y": 0 },
   "targets": [
    {
     "expr": "sum by (queue) (rate(rabbitmq_queue_messages_published_total[$__rate_interval]))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Queue Size",
   "type": "stat",
   "gridPos": { "h": 13, "w": 6, "x": 18, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "rabbitmq_queue_messages_ready", "legendFormat": "{{queue}}" }
   ]
  },
  {
   "title": "Channels Opened and Closed",
   "type": "timeseries",
   "gridPos": { "h": 12, "w": 24, "x": 0, "y": 13 },
   "targets": [
    { "expr": "rabbitmq_channels_closed_total", "legendFormat": "Closed" },
    { "expr": "rabbitmq_channels_opened_total", "legendFormat": "Opened" },
    {
     "expr": "rabbitmq_channels_opened_total-rabbitmq_channels_closed_total",
     "legendFormat": "Active"
    }
   ]
  },
  {
   "title": "Messages published per channel",
   "type": "timeseries",
   "gridPos": { "h": 14, "w": 24, "x": 0, "y": 25 },
   "targets": [
    {
     "expr": "rabbitmq_channel_messages_published_total",
     "legendFormat": "{{channel}}"
    }
   ]
  }
 ]
}