receivers:
  otlp:
    protocols:
      grpc:
      http:
  prometheus:
    config:
      scrape_configs:
      - job_name: 'rabbitmq'
        metrics_path: '/metrics/per-object'
        static_configs:
        - targets: ['rabbitmq:15692']

processors:
  filter/excludeerlang:
    metrics:
      exclude:
        match_type: regexp
        metric_names:
          - erlang_.*
  batch:
      
exporters:
  prometheus:
    endpoint: 0.0.0.0:8889

  otlp/tempo-traces:
    endpoint: tempo:4317
    tls:
      insecure: true

  loki:
    endpoint: http://loki:3100/loki/api/v1/push
    tls:
      insecure: true

service: 
  pipelines:
    metrics:
      receivers: [otlp, prometheus]
      processors: [filter/excludeerlang]
      exporters: [prometheus]
    traces:
      receivers: [otlp]
      processors: []
      exporters: [otlp/tempo-traces]
    logs:
      receivers: [otlp]
      processors: []
      exporters: [loki]